// // This file was generated by Prisma, and assumes you have installed the following:
// // npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });



// import "dotenv/config"
// require("dotenv").config();
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",

//   datasource: {
//     url: process.env.DATABASE_URL,
//   },

//   migrations: {
//     // seed: "npx ts-node prisma/seed.ts",
//     seed: "node prisma/seed.js",
//   },
// });


import "dotenv/config";

export default {
  schema: "prisma/schema.prisma",
  datasource: {
    url: process.env.DATABASE_URL,
  },
  migrations: {
    seed: "node prisma/seed.js",
  },
};